VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "IAdd"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Function Add(ObjAdd As INamed, Optional Check As Boolean = False) As INamed
  
End Function

Public Sub ToListBox(LB As ListBox)

End Sub

Public Function GetByName(StrName As String) As IAdd

End Function

Public Property Get CurrentObj() As INamed

End Property

